version: '3.5'

services:
  db:
    container_name: pg_database
    image: flowers_mega
    build: ./database
    restart: always
    environment:
      - POSTGRES_PASSWORD=gst135bce
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  app:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: nest-docker-postgres
    env_file: backend/.development.env
    environment:
      - PORT=${PORT}
    ports:
      - '5000:5000'
    depends_on:
      - db
    volumes:
      - ./backend:/backend

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=gst135bce
    ports:
      - '5050:80'
    depends_on:
      - db