services:
  db:
    restart: always
    build: ./database
    env_file:
      - ./backend/.production.env
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./backups:/var/lib/postgresql/backups
    ports:
      - '5432:5432'
  # app:
  #   container_name: app
  #   image: flowers_mega
  #   build: ./backend
  #   env_file: ./backend/.production.env
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./backend:/app
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    env_file:
      - ./backend/.production.env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_ADDRS=${PGADMIN_LISTEN_ADDRS}
      - PGADMIN_SERVER_URL=${PGADMIN_SERVER_URL}
    ports:
      - '5050:80'
    depends_on:
      - db
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450